format = """
$directory\
$cmd_duration\
$status\
$fill\
$python\
$git_branch\
$git_status\
$username\
$hostname\
$time\
$line_break\
$character\
"""
add_newline = false

[character]
disabled = false
success_symbol = "❯"
error_symbol = "❯"
vicmd_symbol = "❮"
format = "[$symbol](bold bright-white) "

[cmd_duration]
disabled = false
min_time = 2_000
show_milliseconds = false
style = "bold yellow"
format = "[$duration]($style)"

[directory]
disabled = false
truncation_length = 0
truncate_to_repo = false
fish_style_pwd_dir_length = 2
read_only = " "
read_only_style = "red"
style = "bold green"
format = "[$path]($style)[$read_only]($read_only_style) "

[fill]
disabled = false
symbol = " "
style = ""

[python]
disabled = false
symbol = ""
style = "yellow"
format = "[$symbol (\\($virtualenv\\))]($style)"

[git_branch]
disabled = false
symbol = ""
truncation_length = 8
truncation_symbol = "..."
format = " [$symbol](bold red)[$branch](white)"

[git_status]
disabled = false
modified = "*"
style = "bold dimmed red"
format = "[$modified$ahead_behind]($style)"

[hostname]
disabled = false
ssh_only = false
trim_at = "."
format = "@[$hostname](dimmed white)"

[line_break]
disabled = false

[status]
disabled = false
style = "bold red"
format = "[\\[$status\\]]($style)"

[time]
disabled = false
time_format = "%T"
format = " [$time](dimmed white)"

[username]
disabled = false
show_always = true
style_root = "bold red"
style_user = "dimmed bright-green"
format = " [$user]($style)"
